apiVersion: apps/v1
kind: Deployment
metadata:
  name: vm-vscode
  namespace: default
spec:
  replicas: 10
  selector:
    matchLabels:
      app: vscode
  template:
    metadata:
      labels:
        app: vscode
    spec:
      containers:
        - name: vscode
          image: codercom/code-server:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /home/coder/project
              name: vscode-data
            - name: vscode-volume
              mountPath: /home/coder/.config/code-server/config.yaml
              subPath: config.yaml
      volumes:
        - name: vscode-data
          persistentVolumeClaim:
            claimName: code-server-pvc
        - name: vscode-volume
          configMap:
            name: vscode-config
