http:
    routers:
        code-server-router:
        rule: "HostRegexp(`{username:[a-zA-Z0-9]+}.example.com`)"
        entryPoints:
            - websecure
        tls:
            certResolver: myresolver
        service: code-server-service

    services:
        code-server-service:
        loadBalancer:
            servers:
            - url: "http://code-server-service:8080"